# Generated by Django 4.0.4 on 2022-06-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamestat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamestat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamestat', to='gamestat.games'),
        ),
        migrations.AddField(
            model_name='games',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
