# Generated by Django 4.0.4 on 2022-06-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'GAMES PLAYED'},
        ),
        migrations.AlterModelOptions(
            name='gamestat',
            options={'verbose_name_plural': 'GAME STATISTICS'},
        ),
    ]
