# Generated by Django 4.0.4 on 2023-01-21 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamestat', '0003_alter_games_options_alter_gamestat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='games',
            unique_together={('name', 'created_by')},
        ),
    ]
