# Generated by Django 4.0.4 on 2023-01-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestat', '0004_alter_games_options_alter_games_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='gamestat',
            options={'verbose_name_plural': 'Game Statistics'},
        ),
        migrations.AddField(
            model_name='gamestat',
            name='win',
            field=models.BooleanField(null=True),
        ),
    ]
