# Generated by Django 4.1.6 on 2023-03-23 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gamestat", "0005_alter_games_options_alter_gamestat_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gamestat",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gamestat",
                to="gamestat.games",
            ),
        ),
    ]
